export { default as LineChart } from './component/LineChart/LineChart';
export { default as ColumnChart } from './component/BarChart/ColumnChart';
export { default as BarChart } from './component/BarChart/BarChart';
export { default as SlopeChart } from './component/LineChart/SlopeChart';
export { default as LollipopChart } from './component/OtherCharts/LollipopChart';
export { default as CircularBarChart } from './component/BarChart/CircularBarChart';
export { default as PopulationChart } from './component/OtherCharts/PopulationChart';
export { default as NightingaleChart } from './component/OtherCharts/NightingaleChart';
export { default as PieChart } from './component/OtherCharts/PieChart';
export type { LineChartProps, ColumnChartProps, SlopeChartProps, BarChartProps, LollipopChartProps, PopulationChartProps, PieChartProps } from './interfaces/types';